(function_definition body: (compound_statement (#set! role function)) @subtree)
(struct_specifier (field_declaration_list (#set! role type)) @subtree)
(union_specifier (field_declaration_list (#set! role type)) @subtree)
(enum_specifier (enumerator_list (#set! role type)) @subtree)
(if_statement (compound_statement (#set! role block)) @subtree)
(switch_statement (compound_statement (#set! role block)) @subtree)
(for_statement (compound_statement (#set! role block)) @subtree)
(do_statement (compound_statement (#set! role block)) @subtree)
(while_statement (compound_statement (#set! role block)) @subtree)
(preproc_function_def (preproc_arg (#set! role block)) @subtree)
(method_definition body: ((_) (#set! role function)) @subtree)
(synchronized_statement (compound_statement (#set! role block)) @subtree)
(autoreleasepool_statement (compound_statement (#set! role block)) @subtree)
(category_interface name: (_) @start ("@end") @end.after (#set! role type))
(category_interface category: (_) @start ("@end") @end.after (#set! role type))
(class_interface name: (_) @start ("@end") @end.after (#set! role type))
(class_implementation name: (_) @start ("@end") @end.after (#set! role type))
(protocol_declaration name: (_) @start ("@end") @end.after (#set! role type))
